theme = "rose_pine"

[editor]
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
scrolloff = 5
shell = ["zsh", "-c"]
true-color = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"esc" = [":wa"]

C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

"A-w" = ":buffer-close"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.L]
a = "@|hx-ai<space>-f<space>'<C-r>%'<ret>"
A = "@|hx-ai<space>-f<space>'<C-r>%'"

s = "@|hx-sort<ret>"
t = "@|hx-tags<ret>sxxx<ret>c"

[keys.select.L]
a = "@|hx-ai<space>-f<space>'<C-r>%'<ret>"
A = "@|hx-ai<space>-f<space>'<C-r>%'"

s = "@|hx-sort<ret>"
t = "@|hx-tags<ret>sxxx<ret>c"
