theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
true-color = true
scrolloff = 10
cursorline = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"esc" = [":wa"]

C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

"A-w" = ":buffer-close"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
